package ejemplo.repository.derby;

import ejemplo.dao.UsuarioDAO;
import ejemplo.entity.Usuario;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Versión Derby de MySQLUsuarioDAO. Compará las dos clases lado a lado:
 * el CRUD es idéntico, pero el SQL NO es portable. Esa es la razón de fondo
 * por la que hace falta una familia de DAOs por motor (y por lo tanto, un Abstract Factory).
 */
public class DerbyUsuarioDAO implements UsuarioDAO {

    private final Connection cn;

    public DerbyUsuarioDAO(Connection cn) {
        this.cn = cn;
        crearTablaSiNoExiste();
    }

    /**
     * DIFERENCIA 1: Derby no soporta "CREATE TABLE IF NOT EXISTS".
     * Hay que intentar el CREATE y descartar el error "el objeto ya existe" (SQLState X0Y32).
     *
     * DIFERENCIA 2: en vez de AUTO_INCREMENT, Derby usa "GENERATED BY DEFAULT AS IDENTITY".
     */
    private void crearTablaSiNoExiste() {
        final String sql = "CREATE TABLE usuarios (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "nombre VARCHAR(100) NOT NULL," +
                "email VARCHAR(120) NOT NULL UNIQUE," +
                "edad INTEGER" +
                ")";
        ejecutarDDL(sql, "tabla 'usuarios'");
    }

    /** Reemplazo del "CREATE TABLE IF NOT EXISTS" de MySQL: ignora el objeto ya existente. */
    private void ejecutarDDL(String ddl, String queSeCrea) {
        try (Statement st = cn.createStatement()) {
            st.execute(ddl);
        } catch (SQLException e) {
            if (!"X0Y32".equals(e.getSQLState())) { // X0Y32 = el objeto ya existe
                throw new RuntimeException("Error creando " + queSeCrea, e);
            }
        }
    }

    @Override
    public Usuario findById(Long id) {
        final String sql = "SELECT id, nombre, email, edad FROM usuarios WHERE id = ?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? map(rs) : null;
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error en findById", e);
        }
    }

    @Override
    public List<Usuario> findAll() {
        final String sql = "SELECT id, nombre, email, edad FROM usuarios";
        List<Usuario> out = new ArrayList<>();
        try (PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) out.add(map(rs));
        } catch (SQLException e) {
            throw new RuntimeException("Error en findAll", e);
        }
        return out;
    }

    @Override
    public void create(Usuario u) {
        final String sql = "INSERT INTO usuarios (nombre, email, edad) VALUES (?, ?, ?)";
        try (PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, u.getNombre());
            ps.setString(2, u.getEmail());
            if (u.getEdad() == null) ps.setNull(3, Types.INTEGER); else ps.setInt(3, u.getEdad());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) u.setId(keys.getLong(1));
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error en create", e);
        }
    }

    @Override
    public void update(Usuario u) {
        final String sql = "UPDATE usuarios SET nombre = ?, email = ?, edad = ? WHERE id = ?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, u.getNombre());
            ps.setString(2, u.getEmail());
            if (u.getEdad() == null) ps.setNull(3, Types.INTEGER); else ps.setInt(3, u.getEdad());
            ps.setLong(4, u.getId());
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en update", e);
        }
    }

    @Override
    public void delete(Long id) {
        final String sql = "DELETE FROM usuarios WHERE id = ?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en delete", e);
        }
    }

    /**
     * DIFERENCIA 3: "ALTER TABLE usuarios AUTO_INCREMENT = 1" no existe en Derby.
     * El equivalente es reiniciar la columna IDENTITY.
     */
    @Override
    public void deleteAll() {
        try (Statement st = cn.createStatement()) {
            st.executeUpdate("DELETE FROM usuarios");
            st.execute("ALTER TABLE usuarios ALTER COLUMN id RESTART WITH 1");
        } catch (SQLException e) {
            throw new RuntimeException("Error borrando 'usuarios'", e);
        }
    }

    // ---- mapper privado (idéntico al de MySQL: el ResultSet sí es portable) ----
    private Usuario map(ResultSet rs) throws SQLException {
        Usuario u = new Usuario();
        u.setId(rs.getLong("id"));
        u.setNombre(rs.getString("nombre"));
        u.setEmail(rs.getString("email"));
        int edad = rs.getInt("edad");
        u.setEdad(rs.wasNull() ? null : edad);
        return u;
    }
}
