package ejemplo.repository.derby;

import ejemplo.dao.PedidoDAO;
import ejemplo.dto.TopProducto;
import ejemplo.entity.Pedido;
import ejemplo.entity.PedidoEstado;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Versión Derby de MySQLPedidoDAO. Es el DAO con MÁS diferencias de SQL:
 * mirá findTopProductByUnits(), donde la consulta hay que reescribirla de verdad.
 */
public class DerbyPedidoDAO implements PedidoDAO {

    private final Connection cn;

    public DerbyPedidoDAO(Connection cn) {
        this.cn = cn;
        crearTablaSiNoExiste();
    }

    /**
     * Asegura tabla usuarios (FK) y crea pedidos.
     *
     * Diferencias con MySQL:
     *  - No existe "CREATE TABLE IF NOT EXISTS": hay que descartar el SQLState X0Y32,
     *    y por eso cada sentencia se ejecuta por separado y no todas en un mismo try.
     *  - AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY.
     *  - FLOAT -> REAL.
     *  - El "INDEX ..." declarado dentro del CREATE TABLE no existe en Derby:
     *    va en una sentencia CREATE INDEX aparte.
     */
    private void crearTablaSiNoExiste() {
        final String sqlUsuarios = "CREATE TABLE usuarios (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "nombre VARCHAR(100) NOT NULL," +
                "email VARCHAR(120) NOT NULL UNIQUE," +
                "edad INTEGER" +
                ")";
        final String sql = "CREATE TABLE pedidos (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "usuario_id BIGINT NOT NULL," +
                "estado VARCHAR(20) NOT NULL," +
                "total REAL DEFAULT 0," +
                "CONSTRAINT fk_pedido_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)" +
                ")";
        final String sqlIndice = "CREATE INDEX idx_pedidos_usuario ON pedidos(usuario_id)";

        ejecutarDDL(sqlUsuarios, "tabla 'usuarios'");
        ejecutarDDL(sql, "tabla 'pedidos'");
        ejecutarDDL(sqlIndice, "índice 'idx_pedidos_usuario'");
    }

    /** Reemplazo del "CREATE TABLE IF NOT EXISTS" de MySQL: ignora el objeto ya existente. */
    private void ejecutarDDL(String ddl, String queSeCrea) {
        try (Statement st = cn.createStatement()) {
            st.execute(ddl);
        } catch (SQLException e) {
            if (!"X0Y32".equals(e.getSQLState())) { // X0Y32 = el objeto ya existe
                throw new RuntimeException("Error creando " + queSeCrea, e);
            }
        }
    }

    @Override
    public Pedido findById(Long id) {
        final String sql = "SELECT id, usuario_id, estado, total FROM pedidos WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? map(rs) : null;
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error en findById(pedido)", e);
        }
    }

    @Override
    public List<Pedido> findAll() {
        final String sql = "SELECT id, usuario_id, estado, total FROM pedidos";
        List<Pedido> out = new ArrayList<>();
        try (PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) out.add(map(rs));
        } catch (SQLException e) {
            throw new RuntimeException("Error en findAll(pedido)", e);
        }
        return out;
    }

    @Override
    public List<Pedido> findByUsuario(Long usuarioId) {
        final String sql = "SELECT id, usuario_id, estado, total FROM pedidos WHERE usuario_id=?";
        List<Pedido> out = new ArrayList<>();
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, usuarioId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) out.add(map(rs));
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error en findByUsuario(pedido)", e);
        }
        return out;
    }

    @Override
    public void create(Pedido p) {
        final String sql = "INSERT INTO pedidos (usuario_id, estado, total) VALUES (?,?,?)";
        try (PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setLong(1, p.getUsuarioId());
            ps.setString(2, (p.getEstado() != null ? p.getEstado() : PedidoEstado.BORRADOR).name());
            if (p.getTotal() == null) ps.setNull(3, Types.REAL); else ps.setFloat(3, p.getTotal());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) { if (keys.next()) p.setId(keys.getLong(1)); }
        } catch (SQLException e) {
            throw new RuntimeException("Error en create(pedido)", e);
        }
    }

    @Override
    public void update(Pedido p) {
        final String sql = "UPDATE pedidos SET usuario_id=?, estado=?, total=? WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, p.getUsuarioId());
            ps.setString(2, p.getEstado().name());
            if (p.getTotal() == null) ps.setNull(3, Types.REAL); else ps.setFloat(3, p.getTotal());
            ps.setLong(4, p.getId());
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en update(pedido)", e);
        }
    }

    @Override
    public void updateEstado(Long pedidoId, PedidoEstado nuevoEstado) {
        final String sql = "UPDATE pedidos SET estado=? WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, nuevoEstado.name());
            ps.setLong(2, pedidoId);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en updateEstado(pedido)", e);
        }
    }

    @Override
    public void updateTotal(Long pedidoId, Float nuevoTotal) {
        final String sql = "UPDATE pedidos SET total=? WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            if (nuevoTotal == null) ps.setNull(1, Types.REAL); else ps.setFloat(1, nuevoTotal);
            ps.setLong(2, pedidoId);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en updateTotal(pedido)", e);
        }
    }

    @Override
    public void delete(Long id) {
        final String sql = "DELETE FROM pedidos WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en delete(pedido)", e);
        }
    }

    @Override
    public void deleteAll() {
        try (Statement st = cn.createStatement()) {
            // Padre: NUNCA TRUNCATE con FKs. Usá DELETE y luego reiniciá el contador.
            // Los detalles se borran solos por el ON DELETE CASCADE de detalles_pedido.
            st.executeUpdate("DELETE FROM pedidos");
            // En MySQL: ALTER TABLE pedidos AUTO_INCREMENT = 1
            st.executeUpdate("ALTER TABLE pedidos ALTER COLUMN id RESTART WITH 1");
        } catch (SQLException e) {
            throw new RuntimeException("Error borrando 'pedidos'", e);
        }
    }

    private Pedido map(ResultSet rs) throws SQLException {
        Pedido p = new Pedido();
        p.setId(rs.getLong("id"));
        p.setUsuarioId(rs.getLong("usuario_id"));
        String est = rs.getString("estado");
        p.setEstado(est == null ? PedidoEstado.BORRADOR : PedidoEstado.valueOf(est));
        float t = rs.getFloat("total");
        p.setTotal(rs.wasNull() ? null : t);
        return p;
    }

    /**
     * ACÁ ESTÁ LA DIFERENCIA MÁS INTERESANTE. Compará con MySQLPedidoDAO.findTopProductByUnits():
     *
     *  1) "LIMIT 1"  ->  "FETCH FIRST 1 ROWS ONLY" (sintaxis del estándar SQL, la de MySQL no existe en Derby).
     *
     *  2) GROUP BY: MySQL permite seleccionar p.nombre agrupando solo por d.producto_id.
     *     Derby aplica el estándar: TODA columna del SELECT que no sea un agregado
     *     tiene que estar en el GROUP BY. Por eso acá va "GROUP BY d.producto_id, p.nombre".
     *
     *  3) CAST a DECIMAL: sumar columnas REAL da un REAL, y leerlo con getBigDecimal()
     *     arrastra el error de redondeo del punto flotante. El CAST lo evita.
     */
    @Override
    public Optional<TopProducto> findTopProductByUnits() {
        String sql = """
            SELECT p.nombre AS producto,
                   SUM(d.cantidad)                                          AS unidades_vendidas,
                   CAST(SUM(d.cantidad * d.precio_unitario) AS DECIMAL(12,2)) AS ingreso_total
            FROM detalles_pedido d
            JOIN productos p ON p.id = d.producto_id
            GROUP BY d.producto_id, p.nombre
            ORDER BY unidades_vendidas DESC
            FETCH FIRST 1 ROWS ONLY
        """;
        try (Statement st = cn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            if (rs.next()) {
                return Optional.of(new TopProducto(
                        rs.getString("producto"),
                        rs.getLong("unidades_vendidas"),
                        rs.getBigDecimal("ingreso_total")
                ));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new RuntimeException("Error consultando top product", e);
        }
    }
}
