package ejemplo.repository.derby;

import ejemplo.dao.ProductoDAO;
import ejemplo.entity.Producto;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Versión Derby de MySQLProductoDAO.
 * El CRUD es idéntico; lo único que cambia es el DDL y el reinicio del contador.
 */
public class DerbyProductoDAO implements ProductoDAO {

    private final Connection cn;

    public DerbyProductoDAO(Connection cn) {
        this.cn = cn;
        crearTablaSiNoExiste();
    }

    /**
     * Diferencias con MySQL:
     *  - No existe "CREATE TABLE IF NOT EXISTS": hay que descartar el SQLState X0Y32.
     *  - AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY.
     *  - FLOAT -> REAL (es el tipo de Derby que mapea exacto a Java float).
     */
    private void crearTablaSiNoExiste() {
        final String sql = "CREATE TABLE productos (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "nombre VARCHAR(120) NOT NULL," +
                "stock INTEGER," +
                "precio REAL" + // <- REAL en Derby (en MySQL era FLOAT)
                ")";
        ejecutarDDL(sql, "tabla 'productos'");
    }

    /** Reemplazo del "CREATE TABLE IF NOT EXISTS" de MySQL: ignora el objeto ya existente. */
    private void ejecutarDDL(String ddl, String queSeCrea) {
        try (Statement st = cn.createStatement()) {
            st.execute(ddl);
        } catch (SQLException e) {
            if (!"X0Y32".equals(e.getSQLState())) { // X0Y32 = el objeto ya existe
                throw new RuntimeException("Error creando " + queSeCrea, e);
            }
        }
    }

    @Override
    public Producto findById(Long id) {
        final String sql = "SELECT id, nombre, stock, precio FROM productos WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) { return rs.next() ? map(rs) : null; }
        } catch (SQLException e) { throw new RuntimeException("Error en findById", e); }
    }

    @Override
    public List<Producto> findAll() {
        final String sql = "SELECT id, nombre, stock, precio FROM productos";
        List<Producto> out = new ArrayList<>();
        try (PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) out.add(map(rs));
        } catch (SQLException e) { throw new RuntimeException("Error en findAll", e); }
        return out;
    }

    @Override
    public void create(Producto p) {
        final String sql = "INSERT INTO productos (nombre, stock, precio) VALUES (?,?,?)";
        try (PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, p.getNombre());
            if (p.getStock() == null) ps.setNull(2, Types.INTEGER); else ps.setInt(2, p.getStock());
            // Types.REAL (no Types.FLOAT): la columna es REAL en Derby
            if (p.getPrecio() == null) ps.setNull(3, Types.REAL); else ps.setFloat(3, p.getPrecio());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) { if (keys.next()) p.setId(keys.getLong(1)); }
        } catch (SQLException e) { throw new RuntimeException("Error en create(producto)", e); }
    }

    @Override
    public void update(Producto p) {
        final String sql = "UPDATE productos SET nombre=?, stock=?, precio=? WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, p.getNombre());
            if (p.getStock() == null) ps.setNull(2, Types.INTEGER); else ps.setInt(2, p.getStock());
            if (p.getPrecio() == null) ps.setNull(3, Types.REAL); else ps.setFloat(3, p.getPrecio());
            ps.setLong(4, p.getId());
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException("Error en update(producto)", e); }
    }

    @Override
    public void delete(Long id) {
        final String sql = "DELETE FROM productos WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            ps.executeUpdate();
        } catch (SQLException e) { throw new RuntimeException("Error en delete(producto)", e); }
    }

    @Override
    public void deleteAll() {
        try (Statement st = cn.createStatement()) {
            st.executeUpdate("DELETE FROM productos");
            // En MySQL: ALTER TABLE productos AUTO_INCREMENT = 1
            st.execute("ALTER TABLE productos ALTER COLUMN id RESTART WITH 1");
        } catch (SQLException e) {
            throw new RuntimeException("Error borrando 'productos'", e);
        }
    }

    // ---- mapper privado (idéntico al de MySQL: el ResultSet sí es portable) ----
    private Producto map(ResultSet rs) throws SQLException {
        Producto p = new Producto();
        p.setId(rs.getLong("id"));
        p.setNombre(rs.getString("nombre"));
        int stock = rs.getInt("stock");
        p.setStock(rs.wasNull() ? null : stock);

        float f = rs.getFloat("precio");                     // getFloat devuelve primitivo
        p.setPrecio(rs.wasNull() ? null : Float.valueOf(f)); // convertimos a wrapper si no es null

        return p;
    }
}
