package ejemplo.repository.derby;

import ejemplo.dao.DetallePedidoDAO;
import ejemplo.entity.DetallePedido;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Versión Derby de MySQLDetallePedidoDAO.
 * El CRUD es idéntico; cambia el DDL y el reinicio del contador.
 */
public class DerbyDetallePedidoDAO implements DetallePedidoDAO {

    private final Connection cn;

    public DerbyDetallePedidoDAO(Connection cn) {
        this.cn = cn;
        crearTablasSiNoExisten();
    }

    /**
     * Asegura las tablas referenciadas y crea detalles_pedido.
     *
     * Diferencias con MySQL:
     *  - No existe "CREATE TABLE IF NOT EXISTS": hay que descartar el SQLState X0Y32,
     *    y por eso cada sentencia se ejecuta por separado y no todas en un mismo try.
     *  - AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY.
     *  - FLOAT -> REAL.
     *  - Los "INDEX ..." declarados dentro del CREATE TABLE van en CREATE INDEX aparte.
     *  - Hay que crear también 'usuarios': pedidos tiene una FK contra ella y Derby
     *    valida las claves foráneas al crear la tabla, así que el orden importa.
     */
    private void crearTablasSiNoExisten() {
        final String sqlUsuarios = "CREATE TABLE usuarios (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "nombre VARCHAR(100) NOT NULL," +
                "email VARCHAR(120) NOT NULL UNIQUE," +
                "edad INTEGER" +
                ")";
        final String sqlProductos = "CREATE TABLE productos (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "nombre VARCHAR(120) NOT NULL," +
                "stock INTEGER," +
                "precio REAL" +
                ")";
        final String sqlPedidos = "CREATE TABLE pedidos (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "usuario_id BIGINT NOT NULL," +
                "estado VARCHAR(20) NOT NULL," +
                "total REAL DEFAULT 0," +
                "CONSTRAINT fk_pedido_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)" +
                ")";
        final String sqlIndicePedidos = "CREATE INDEX idx_pedidos_usuario ON pedidos(usuario_id)";
        final String sql = "CREATE TABLE detalles_pedido (" +
                "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                "pedido_id BIGINT NOT NULL," +
                "producto_id BIGINT NOT NULL," +
                "cantidad INTEGER NOT NULL," +
                "precio_unitario REAL NOT NULL," +
                "subtotal REAL NOT NULL," +
                "CONSTRAINT fk_detalle_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE," +
                "CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES productos(id)" +
                ")";
        final String sqlIndiceDetalle = "CREATE INDEX idx_detalle_pedido ON detalles_pedido(pedido_id)";

        ejecutarDDL(sqlUsuarios, "tabla 'usuarios'");
        ejecutarDDL(sqlProductos, "tabla 'productos'");
        ejecutarDDL(sqlPedidos, "tabla 'pedidos'");
        ejecutarDDL(sqlIndicePedidos, "índice 'idx_pedidos_usuario'");
        ejecutarDDL(sql, "tabla 'detalles_pedido'");
        ejecutarDDL(sqlIndiceDetalle, "índice 'idx_detalle_pedido'");
    }

    /** Reemplazo del "CREATE TABLE IF NOT EXISTS" de MySQL: ignora el objeto ya existente. */
    private void ejecutarDDL(String ddl, String queSeCrea) {
        try (Statement st = cn.createStatement()) {
            st.execute(ddl);
        } catch (SQLException e) {
            if (!"X0Y32".equals(e.getSQLState())) { // X0Y32 = el objeto ya existe
                throw new RuntimeException("Error creando " + queSeCrea, e);
            }
        }
    }

    @Override
    public DetallePedido findById(Long id) {
        final String sql = "SELECT id, pedido_id, producto_id, cantidad, precio_unitario, subtotal FROM detalles_pedido WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? map(rs) : null;
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error en findById(detalle)", e);
        }
    }

    @Override
    public List<DetallePedido> findByPedido(Long pedidoId) {
        final String sql = "SELECT id, pedido_id, producto_id, cantidad, precio_unitario, subtotal FROM detalles_pedido WHERE pedido_id=?";
        List<DetallePedido> out = new ArrayList<>();
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, pedidoId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) out.add(map(rs));
            }
        } catch (SQLException e) {
            throw new RuntimeException("Error en findByPedido(detalle)", e);
        }
        return out;
    }

    @Override
    public void create(DetallePedido d) {
        // Calcula subtotal si viene null
        if (d.getSubtotal() == null && d.getCantidad() != null && d.getPrecioUnitario() != null) {
            d.setSubtotal(d.getCantidad() * d.getPrecioUnitario());
        }
        final String sql = "INSERT INTO detalles_pedido (pedido_id, producto_id, cantidad, precio_unitario, subtotal) VALUES (?,?,?,?,?)";
        try (PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setLong(1, d.getPedidoId());
            ps.setLong(2, d.getProductoId());
            ps.setInt(3, d.getCantidad());
            ps.setFloat(4, d.getPrecioUnitario());
            ps.setFloat(5, d.getSubtotal());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) { if (keys.next()) d.setId(keys.getLong(1)); }
        } catch (SQLException e) {
            throw new RuntimeException("Error en create(detalle)", e);
        }
    }

    @Override
    public void update(DetallePedido d) {
        if (d.getSubtotal() == null && d.getCantidad() != null && d.getPrecioUnitario() != null) {
            d.setSubtotal(d.getCantidad() * d.getPrecioUnitario());
        }
        final String sql = "UPDATE detalles_pedido SET pedido_id=?, producto_id=?, cantidad=?, precio_unitario=?, subtotal=? WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, d.getPedidoId());
            ps.setLong(2, d.getProductoId());
            ps.setInt(3, d.getCantidad());
            ps.setFloat(4, d.getPrecioUnitario());
            ps.setFloat(5, d.getSubtotal());
            ps.setLong(6, d.getId());
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en update(detalle)", e);
        }
    }

    @Override
    public void delete(Long id) {
        final String sql = "DELETE FROM detalles_pedido WHERE id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, id);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en delete(detalle)", e);
        }
    }

    @Override
    public void deleteByPedido(Long pedidoId) {
        final String sql = "DELETE FROM detalles_pedido WHERE pedido_id=?";
        try (PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setLong(1, pedidoId);
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Error en deleteByPedido(detalle)", e);
        }
    }

    @Override
    public void deleteAll() {
        try (Statement st = cn.createStatement()) {
            // Hijo primero
            st.executeUpdate("DELETE FROM detalles_pedido");
            // En MySQL: ALTER TABLE detalles_pedido AUTO_INCREMENT = 1
            st.executeUpdate("ALTER TABLE detalles_pedido ALTER COLUMN id RESTART WITH 1");
        } catch (SQLException e) {
            throw new RuntimeException("Error borrando 'detalles_pedido'", e);
        }
    }

    // ---- mapper privado (idéntico al de MySQL: el ResultSet sí es portable) ----
    private DetallePedido map(ResultSet rs) throws SQLException {
        DetallePedido d = new DetallePedido();
        d.setId(rs.getLong("id"));
        d.setPedidoId(rs.getLong("pedido_id"));
        d.setProductoId(rs.getLong("producto_id"));
        d.setCantidad(rs.getInt("cantidad"));
        d.setPrecioUnitario(rs.getFloat("precio_unitario"));
        d.setSubtotal(rs.getFloat("subtotal"));
        return d;
    }
}
